spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/himitsudougu_db
spring.datasource.username=postgres
spring.datasource.password=new_password